synolia/SyliusSchedulerCommandPlugin

.travis.yml
Before
Job | PHP | OS | State
-- | -- | -- | --
1.1 | 7.2 | Linux | passed
1.2 | 7.3 | Linux | passed
After
Job | PHP | ENV | OS | State | Notes
-- | -- | -- | -- | -- | --
3.1 | 7.2 | DEPENDENCY_VERSIONS="sylius/sylius:1.5.*" | Linux | received |  
3.2 | 7.2 | DEPENDENCY_VERSIONS="sylius/sylius:1.6.*" | Linux | started |  
3.3 | 7.3 | DEPENDENCY_VERSIONS="sylius/sylius:1.5.*" | Linux | received |  
3.4 | 7.3 | DEPENDENCY_VERSIONS="sylius/sylius:1.6.*" | Linux | created |  
3.5 | 7.2 | DEPENDENCY_VERSIONS="sylius/sylius:dev-master" | Linux | created | This job is allowed to fail.
3.6 | 7.3 | DEPENDENCY_VERSIONS="sylius/sylius:dev-master" | Linux | created | This job is allowed to fail.
=> fix travis jobs

README.md
=> install with symfony flex

src/Command/SynoliaSchedulerRunCommand.php, src/Service/ExecuteScheduleCommand.php
Steam output from command can now created from stdout or stderr.
=> command output to file

composer.json, ruleset/phpstan.neon
=> extends compatibilities in requirements

.github/PULL_REQUEST_TEMPLATE.md
=> add license to PR request

.github/workflows/tests.yaml
=> clean github actions debug

composer.json, ruleset/.php_md.xml, src/Resources/translations/messages.fr.yml
=> fix translation fr

composer.json, ruleset/phpstan.neon, src/Command/SynoliaSchedulerRunCommand.php, src/Grid/FieldType/ScheduledCommandExecutionTimeType.php, src/Grid/FieldType/ScheduledCommandHumanReadableExpressionType.php, src/Grid/FieldType/ScheduledCommandUrlType.php
Following a question from @paintras on Slack, I noticed that the library was abandoned. So I used his fork.
This PR require #27 for fixed tests.
=> Change php cron expression parser

.github/workflows/tests.yaml, README.md, composer.json, tests/Application/.env
=> [CI] drop old sylius versions and add new ones

README.md
=> fig badge ci

src/Resources/translations/messages.nl.yml
| Fixed issue   | -
Add translation file for Dutch
=> Dutch translations

src/Resources/config/admin_routing.yaml, src/Resources/translations/messages.en.yml, src/Resources/translations/messages.fr.yml, src/Resources/translations/messages.nl.yml
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Fixed issue   | #... 
=> SYLIUS-189-Add-role-for-sylius-plus-Rbac

src/Resources/config/config.yaml, src/Resources/config/ui.yaml, src/Resources/public/column/index.js, src/Resources/public/controller/index.css, src/Resources/public/controller/index.js, src/Resources/views/Controller/css.html.twig, src/Resources/views/Controller/js.html.twig, src/Resources/views/Controller/modal.html.twig, src/Resources/views/Controller/show.html.twig, src/Resources/views/Grid/Column/js.html.twig, src/Resources/views/Grid/Column/log_file.html.twig
=> feature: improve log display

.github/workflows/ci.yaml, Makefile, README.md, ruleset/.php_md.xml, spec/Command/SynoliaSchedulerRunCommandSpec.php, src/Checker/EveryMinuteIsDueChecker.php, src/Checker/IsDueCheckerInterface.php, src/Checker/SoftLimitThresholdIsDueChecker.php, src/Command/SynoliaSchedulerRunCommand.php, src/Components/Exceptions/Checker/IsNotDueException.php, src/Entity/Command.php, src/Entity/CommandInterface.php, src/Entity/ScheduledCommand.php, src/Entity/ScheduledCommandInterface.php, src/Grid/FieldType/ScheduledCommandExecutionTimeType.php, src/Migrations/Version20210828114655.php, src/Repository/ScheduledCommandRepository.php, src/Repository/ScheduledCommandRepositoryInterface.php, src/Resources/config/services.yaml, src/Service/ScheduledCommandPlanner.php, src/Voter/IsDueVoter.php, src/Voter/IsDueVoterInterface.php, tests/Behat/Context/Cli/CliContext.php, tests/PHPUnit/AbstractIsDueTest.php, tests/PHPUnit/Checker/EveryMinuteIsDueCheckerTest.php, tests/PHPUnit/Checker/SoftLimitThresholdIsDueCheckerTest.php, tests/PHPUnit/Voter/IsDueVoterTest.php
| BC breaks?    | yes
Added IsDue voter to allow better check when using cloud service that run cron only every X minutes even if cron is set to run every minutes.
=> Added IsDue voter and fixed timeout for long-running scheduled command

composer.json
=> updated minimal php version to PHP 7.4

UPGRADE.md
=> Added Upgrade instructions for migration from ^2.0 to ^3.0

README.md
=> added specification for v3 till recipes contrib is updated

Makefile, README.md, src/Command/PurgeScheduledCommandCommand.php, src/DoctrineEvent/ScheduledCommandPostRemoveEvent.php, src/Repository/ScheduledCommandRepository.php, src/Repository/ScheduledCommandRepositoryInterface.php, src/Resources/config/services.yaml, tests/PHPUnit/Command/PurgeScheduledCommandCommandTest.php
=> Add command to clean scheduled commands history

.github/workflows/ci.yaml, README.md, composer.json
=> Update readme Requirements and minor fix

ruleset/phpstan.neon, src/Runner/ScheduleCommandRunner.php, tests/Behat/Resources/suites.yml
=> fix long run in phpunit

Makefile, composer.json, grumphp.yml, src/Parser/CommandParser.php
=> fix no command found

.github/workflows/analysis.yaml, .github/workflows/sylius.yaml
=> [DX] Add Symfony 6.2 in CI

.github/workflows/analysis.yaml, .github/workflows/sylius.yaml
=> [DX] GitHub action deprecation

Makefile, src/Command/SynoliaSchedulerRunCommand.php, tests/PHPUnit/Command/SynoliaSchedulerRunCommandTest.php
=> fix execute immediately

src/Entity/Command.php, src/Entity/ScheduledCommand.php
=> [DX] add PHP 8 ORM attributes

composer.json, src/Parser/CommandParser.php, src/Resources/config/services.yaml
=> Better way to extract Command list

.github/workflows/analysis.yaml, .github/workflows/sylius.yaml, src/Command/SynoliaSchedulerRunCommand.php, src/Resources/config/services.yaml
=> [DX] Update and fix CI

Makefile, src/Humanizer/CronExpressionHumanizer.php, src/Resources/config/services.yaml
| Fixed issue   | https://github.com/synolia/SyliusSchedulerCommandPlugin/issues/96
Please squash commit, I'm using github web UI right now and I can't squash
=> Add possibility of time date format 12/24
